language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: make test
deploy:
  provider: openshift
  user: ${OPENSHIFT_USER}
  password: ${OPENSHIFT_PASSWORD}
  domain: ${OPENSHIFT_DOMAIN}
